version: "2"
services:
  # front:
  #   command: yarn start
  #   build: frontend/
  #   ports:
  #     - "3000:3000"
  #   expose:
  #     - 3000
  #   networks:
  #     rentbrella_test:
  #       ipv4_address: 172.20.0.6
  cobranca:
    depends_on:
      - rentbrellatestdb
      - basket
    command: ./start.sh
    build: services/cobranca/
    ports:
      - "5002:5002"
    expose:
      - 5002
    networks:
      rentbrella_test:
        ipv4_address: 172.20.0.5
  emprestimo:
    depends_on:
      - rentbrellatestdb
      - basket
    command: ./start.sh
    build: services/emprestimo/
    volumes:
      - ./services/emprestimo:/teste-rentbrella
    ports:
      - "5001:5001"
    expose:
      - 5501
    networks:
      rentbrella_test:
        ipv4_address: 172.20.0.4
  rentbrellatestdb:
    build: database/
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      rentbrella_test:
        ipv4_address: 172.20.0.2
    # environment:
    #   MYSQL_ROOT_USERNAME: "root"
    #   MYSQL_ROOT_PASSWORD: "root"
  basket:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      rentbrella_test:
        ipv4_address: 172.20.0.3
  worker:
    build:
      context: ./services/emprestimo
      dockerfile: ./Dockerfile
    volumes:
      - ./services/emprestimo:/teste-rentbrella
    command: bash -c "rqworker default --worker-ttl 10 --path /emprestimoapp/ -u redis://172.20.0.3"
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      rentbrella_test:
        ipv4_address: 172.20.0.7
    # links:
    #   - rentbrellatestdb
    #   - cobranca
    #   - emprestimo

networks:
    rentbrella_test:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
